#!/usr/bin/env python3
"""Regenerate the WING_REF table in tests/wing_seed.rs from mpmath at 200 bits.

The wing-seed kernel maps (h = |k_log|, q = IG survival) to v = σ√T. The
mpmath-200-bit reference table pins the seed against an oracle that has no
dependency on the Rust kernel itself, so test agreement is independent
evidence of correctness.

Domain: h ∈ {3, 4, 5, 6, 7, 8}, q ∈ {0.01, 0.05, 0.10, 0.20, 0.30}.

Reference equation: the IG-inverse-Gaussian survival relation that maps the
wing parameter pair (h, q) back to v. Schadner's parameterisation is
  q = F_IG(4/v² | 2/h, 1)  (the IG CDF with mean 2/h and shape 1, at 4/v²)
which is equivalent to
  q_surv = 1 - F_IG(4/v² | 2/h, 1).

We invert by mp.findroot.

Run:
  python3 scripts/wing_ref_gen.py > /tmp/wing_ref.txt
then paste the table into tests/wing_seed.rs above the existing WING_REF entries.

Not wired into CI; here for reproducibility.
"""
import mpmath as mp

mp.mp.prec = 200  # 200 bits ≈ 60 decimals


def ig_cdf(x, mu, lam):
    """Inverse-Gaussian CDF F(x | mu, lam) at 200 bits.

        F(x) = Φ( √(λ/x) · (x/μ − 1) ) + exp(2λ/μ) · Φ( −√(λ/x) · (x/μ + 1) )

    Φ via mp.ncdf.
    """
    a = mp.sqrt(lam / x) * (x / mu - 1)
    b = -mp.sqrt(lam / x) * (x / mu + 1)
    return mp.ncdf(a) + mp.exp(2 * lam / mu) * mp.ncdf(b)


def solve_v_for(h, q_surv):
    """Find v such that 1 - ig_cdf(4/v², 2/h, 1) = q_surv."""
    mu = mp.mpf(2) / mp.mpf(h)
    lam = mp.mpf(1)
    target = mp.mpf(q_surv)

    def f(v):
        v = mp.fabs(v)
        if v < mp.mpf("1e-12"):
            v = mp.mpf("1e-12")
        x = mp.mpf(4) / (v * v)
        cdf = ig_cdf(x, mu, lam)
        return (mp.mpf(1) - cdf) - target

    # Initial guess: leading-order W0(h, q).
    z1 = -mp.mpf(mp.qfunc(target).real if False else 0)  # placeholder; use a coarse seed
    # Use a robust bracket-style: scan h-dependent range.
    # In practice v ∈ (0.1, 10.0) covers the (h, q) cells in the table.
    lo = mp.mpf("0.1")
    hi = mp.mpf("10.0")
    root = mp.findroot(f, (lo, hi), solver="anderson", tol=mp.mpf("1e-50"), maxsteps=200)
    return mp.fabs(root)


def main():
    H_VALUES = [3.0, 4.0, 5.0, 6.0, 7.0, 8.0]
    Q_VALUES = [0.01, 0.05, 0.10, 0.20, 0.30]
    print("// Regenerated by scripts/wing_ref_gen.py at mpmath 200-bit precision.")
    print("const WING_REF: &[(f64, f64, f64)] = &[")
    for h in H_VALUES:
        for q in Q_VALUES:
            v = solve_v_for(h, q)
            print(f"    ({h:.1f}, {q:.4f}, {float(v):.17e}),")
    print("];")


if __name__ == "__main__":
    main()
