//! `voltic::schadner_fast` — Schadner IV via Chebyshev seed + one Halley step.
//!
//! The v1.1 "fastest at machine precision" kernel. Same explicit-formula
//! starting point as [`crate::schadner`] (Schadner 2026, arXiv:2604.24480 —
//! the BS call price is the survival function of an inverse Gaussian, so
//! `σ(K, C) = (2/√T)·F_IG⁻¹((1−c)/m; 2/|k|, 1)^(−1/2)`). The IG quantile has
//! no elementary closed form and is itself a root of the IG CDF; this module
//! takes that root by **one Halley step** from a pre-fit Chebyshev seed
//! accurate to ~9e-7 across the canonical domain.
//!
//! ## Why this beats Newton/Halley from CM seed
//!
//! Halley's method is convergence order 3: each step takes residual `e` to
//! `~e³`. The seed quality bounds the achievable precision in N steps:
//!
//! ```text
//!   CM seed       (1%) → Newton (3-4 iters) → conditioning floor
//!   CM seed       (1%) → Halley (2-3 iters) → conditioning floor
//!   Chebyshev seed (1e-7) → Halley (1 iter)   → machine precision
//! ```
//!
//! The Chebyshev seed is the load-bearing piece. It was fit offline (see
//! `tools/fit_seed.py`) by Newton-to-tolerance over a 48×48 Chebyshev node
//! grid in the transformed (ln k, Φ⁻¹ p)-domain, truncated to a 23×23 bivariate
//! Chebyshev expansion of `ln v`. Max absolute seed error on an 80×80 uniform
//! test grid is **8.8e-7** — six orders better than what one Halley needs to
//! land at f64 conditioning floor.
//!
//! ## Halley update derivation
//!
//! Iterate in vol space `v = σ·√T` (better-conditioned than `x = 4/v²`; a
//! tail overshoot in `x` would land at a clamp). Residual:
//!
//! ```text
//!   G(v)   = F_IG(x; μ, 1) − q    with x = 4/v², q = (1 − c)/m, μ = 2/|k|
//!   G'(v)  = −8·f_IG(x)/v³
//!   G''(v) = 64·f'_IG(x)/v⁶ + 24·f_IG(x)/v⁴
//! ```
//!
//! Halley:  `v ← v − 2·G·G' / (2·(G')² − G·G'')`.
//!
//! `f'_IG = f_IG · [μ/(2x²) − 3/(2x) − 1/(2μ²)]` — algebraic, no extra
//! transcendental.
//!
//! ## Clean-room provenance
//!
//! The seed was generated from the published Schadner formula + bracketed
//! Newton against the IG CDF as defined in the paper. No code from
//! [wol-fi/volfi] was read at any point. The 23×23 coefficient table is a
//! direct fit; the implementation is independent.
//!
//! [wol-fi/volfi]: https://github.com/wol-fi/volfi

use std::simd::prelude::*;
use std::simd::StdFloat;

use crate::norm;
use crate::{bs_price_vega, screen, OptionKind};
use crate::{LANES, M, V, VOL_MAX, VOL_MIN};

// Generated by `tools/fit_seed.py`; constants `SEED_*`.
include!("schadner_fast_seed.rs");

// --- A5: public re-exports for `otm_context.rs` ----------------------------
// The split context API needs the seed degree + clamp limits to build the
// (k,T)-only prelude on the caller side. Re-export them under `_PUB` names so
// downstream callers don't accidentally name-shadow private constants if they
// `use schadner_fast::*`.

/// Degree of the bivariate Chebyshev seed (= 12). Public for the
/// [`crate::otm_context`] API.
pub const SEED_DEG_PUB: usize = SEED_DEG;
/// Lower premium-ratio bound of the seed domain. Public for context-prelude.
pub const SEED_P_LO_PUB: f64 = SEED_P_LO;
/// Upper premium-ratio bound of the seed domain. Public for context-prelude.
pub const SEED_P_HI_PUB: f64 = SEED_P_HI;

/// Below this `|k| = |ln(K/F)|` the option is treated as at-the-forward and
/// the formula collapses to the probit (`σ = 2·Φ⁻¹((c+1)/2)/√T`). Below the
/// Chebyshev seed domain (`SEED_K_LO = 0.005`), so any `k < SEED_K_LO` would
/// land us extrapolating; the probit answer is accurate enough at this scale.
const K_PROBIT_THRESHOLD: f64 = 1e-4;

/// Number of Halley iterations after the Chebyshev seed. Swept by the
/// conductor; the public-API NaN contract is preserved by the `implied_vol_fast`
/// wrapper in `crate::lib`, which falls back to the rational kernel on any
/// poisoned lane.
const HALLEY_STEPS: usize = 0;

/// Number of Householder-3 (order-4) iterations after the Halley iterations.
/// A2 sweep: pure Householder, hybrid (1 Halley + 1 HH3), etc.
const HOUSEHOLDER3_STEPS: usize = 3;

/// Vega-scaled acceptance tolerance — accept a lane iff
/// `|price(σ) − price| / vega(σ) < SIGMA_TOL` (i.e. the residual, mapped from
/// price-space into σ-space by the local linearization `dp = vega · dσ`,
/// is below tolerance). σ-direct gate; works in every regime including ATM
/// where the IG residual `G(v)` suffers catastrophic cancellation.
const SIGMA_TOL: f64 = 1e-7;

/// IG(μ, λ=1) CDF, density, and density derivative at `x > 0`, lane-packed.
///
/// **Avenue 1 (cancellation-free)**. The naive form
/// `S = Φ(−a+b) − e^(2/μ)·Φ(−a−b)` loses digits as `μ → ∞` (ATM):
/// both `Φ`-terms approach the same value and `e^(2/μ) → 1`. The identity
///
/// ```text
///   S(x; μ) = ½ · e^(−u²) · [erfcx(u) − erfcx(v)]
/// ```
///
/// with `u = (a−b)/√2`, `v = (a+b)/√2`, is mathematically the same but is
/// FP-stable everywhere: `erfcx` is slowly varying and monotone, so the
/// difference is honest. Derivation: `Φ(−z) = ½ · e^(−z²/2) · erfcx(z/√2)`
/// for `z ≥ 0`; then `v² − u² = 2ab = 2/μ` exactly cancels the `e^(2/μ)`
/// in the original.
///
/// `u` is signed; `v ≥ 0` always. Negative `u` lanes use the reflection
/// `erfcx(−y) = 2·e^(y²) − erfcx(y)`.
/// See module docs for the `f'_IG` derivation.
#[inline]
fn ig_cdf_pdf_dpdf(x: V, mu: V) -> (V, V, V) {
    let sqrt_x = x.sqrt();
    let inv_sqrt_x = V::splat(1.0) / sqrt_x;
    let a = sqrt_x / mu;

    // Cancellation-free survival: S = ½·e^(−u²)·[erfcx(u) − erfcx(v)].
    let frac_1_sqrt_2 = V::splat(core::f64::consts::FRAC_1_SQRT_2);
    let u = (a - inv_sqrt_x) * frac_1_sqrt_2;
    let v = (a + inv_sqrt_x) * frac_1_sqrt_2;

    // Research D fused form (F3 + B1 + reciprocal) saves one exp + one mul
    // per CDF vs the explicit reflect-then-prefactor sequence; see
    // `norm::ig_surv_from_uv` for the analytic collapse.
    let surv = norm::ig_surv_from_uv(u, v);
    let cdf = V::splat(1.0) - surv;

    let two_pi = V::splat(2.0 * core::f64::consts::PI);
    let inv_norm = (two_pi * x * x * x).sqrt();
    let dx = x - mu;
    let pdf = norm::vexp(-(dx * dx) / (V::splat(2.0) * mu * mu * x)) / inv_norm;

    let two = V::splat(2.0);
    let three_halves = V::splat(1.5);
    let factor = V::splat(1.0) / (two * x * x) - three_halves / x - V::splat(1.0) / (two * mu * mu);
    let dpdf = pdf * factor;
    (cdf, pdf, dpdf)
}

/// One Halley step on `G(v) = F_IG(4/v²; μ, 1) − q`, lane-packed.
#[inline]
fn halley_step(v: V, mu: V, q: V) -> V {
    let x = V::splat(4.0) / (v * v);
    let (cdf, pdf, dpdf) = ig_cdf_pdf_dpdf(x, mu);
    let g = cdf - q;
    let v2 = v * v;
    let v3 = v2 * v;
    let v4 = v2 * v2;
    let v6 = v3 * v3;
    let gp = -V::splat(8.0) * pdf / v3;
    let gpp = V::splat(64.0) * dpdf / v6 + V::splat(24.0) * pdf / v4;
    let num = V::splat(2.0) * g * gp;
    let den = V::splat(2.0) * gp * gp - g * gpp;
    let den_safe = den.abs().simd_max(V::splat(1e-300));
    let signed_den = den.is_sign_negative().select(-den_safe, den_safe);
    v - num / signed_den
}

/// One Householder-3 step (convergence order 4) on `G(v) = F_IG(4/v²; μ, 1) − q`,
/// lane-packed. Uses the corrected derivative chain (see module docs):
///   L(x)  = 1/(2x²) − 3/(2x) − 1/(2μ²)
///   L'(x) = −1/x³ + 3/(2x²)
///   f'_IG  = f_IG · L
///   f''_IG = f_IG · (L² + L')
/// G', G'', G''' derived by chain rule from `x = 4/v²`.
/// Householder-3 step: Δv = (6·G·G'² − 3·G²·G'') / (6·G'³ − 6·G·G'·G'' + G²·G''').
///
/// **A5**: also re-exported as [`householder3_step_simd`] (same function, public
/// alias) so the [`crate::otm_context`] split-API path can drive iterations
/// without re-implementing the chain.
#[inline]
fn householder3_step(v: V, mu: V, q: V) -> V {
    let x = V::splat(4.0) / (v * v);
    let (cdf, pdf, _dpdf) = ig_cdf_pdf_dpdf(x, mu);

    // L(x) and L'(x). Recomputed here (rather than threaded out of
    // `ig_cdf_pdf_dpdf`) so we can keep the existing API stable.
    let two = V::splat(2.0);
    let three_halves = V::splat(1.5);
    let inv_x = V::splat(1.0) / x;
    let inv_x2 = inv_x * inv_x;
    let inv_x3 = inv_x2 * inv_x;
    let l = V::splat(0.5) * inv_x2 - three_halves * inv_x - V::splat(1.0) / (two * mu * mu);
    let l_prime = -inv_x3 + three_halves * inv_x2;

    let f = pdf;
    let f_p = f * l;
    let f_pp = f * (l * l + l_prime);

    // v inverse powers
    let inv_v = V::splat(1.0) / v;
    let inv_v2 = inv_v * inv_v;
    let inv_v3 = inv_v2 * inv_v;
    let inv_v4 = inv_v2 * inv_v2;
    let inv_v5 = inv_v4 * inv_v;
    let inv_v6 = inv_v4 * inv_v2;
    let inv_v7 = inv_v6 * inv_v;
    let inv_v9 = inv_v6 * inv_v3;

    let g = cdf - q;
    let gp = -V::splat(8.0) * f * inv_v3;
    let gpp = V::splat(64.0) * f_p * inv_v6 + V::splat(24.0) * f * inv_v4;
    let gppp = -V::splat(512.0) * f_pp * inv_v9
        - V::splat(576.0) * f_p * inv_v7
        - V::splat(96.0) * f * inv_v5;

    let gp2 = gp * gp;
    let gp3 = gp2 * gp;
    let g2 = g * g;
    let num = V::splat(6.0) * g * gp2 - V::splat(3.0) * g2 * gpp;
    let den = V::splat(6.0) * gp3 - V::splat(6.0) * g * gp * gpp + g2 * gppp;
    let den_safe = den.abs().simd_max(V::splat(1e-300));
    let signed_den = den.is_sign_negative().select(-den_safe, den_safe);
    v - num / signed_den
}

/// Bivariate Chebyshev seed: `ln(v) ≈ Σ_m Σ_n c_mn · T_m(u(k)) · T_n(w(p))`,
/// lane-packed. Caller clamps `(k, p)` into the seed domain before calling.
#[inline]
fn cheb_seed(k_abs: V, q: V) -> V {
    // Transform: u(k) = (2·ln(k) − [ln(K_LO)+ln(K_HI)]) / [ln(K_HI)−ln(K_LO)].
    let ln_k = norm::vlog(k_abs);
    let u_centre = V::splat(0.5 * (SEED_LN_K_LO + SEED_LN_K_HI));
    let u_half_width = V::splat(0.5 * (SEED_LN_K_HI - SEED_LN_K_LO));
    let u = (ln_k - u_centre) / u_half_width;

    // Transform: w(p) = (2·logit(p) − [logit(P_LO)+logit(P_HI)]) / [logit(P_HI)−logit(P_LO)].
    //   logit(p) = ln(p / (1 - p))   — ~3 ns vs ~35 ns for phi_inv.
    let logit_q = norm::vlog(q / (V::splat(1.0) - q));
    let w_centre = V::splat(0.5 * (SEED_LOGIT_P_LO + SEED_LOGIT_P_HI));
    let w_half_width = V::splat(0.5 * (SEED_LOGIT_P_HI - SEED_LOGIT_P_LO));
    let w = (logit_q - w_centre) / w_half_width;

    // Chebyshev recurrence: T_0(u) = 1, T_1(u) = u, T_n(u) = 2u·T_{n-1} − T_{n-2}.
    let mut tu = [V::splat(0.0); SEED_DEG + 1];
    let mut tw = [V::splat(0.0); SEED_DEG + 1];
    tu[0] = V::splat(1.0);
    tu[1] = u;
    tw[0] = V::splat(1.0);
    tw[1] = w;
    let two_u = V::splat(2.0) * u;
    let two_w = V::splat(2.0) * w;
    let mut i = 2;
    while i <= SEED_DEG {
        tu[i] = two_u * tu[i - 1] - tu[i - 2];
        tw[i] = two_w * tw[i - 1] - tw[i - 2];
        i += 1;
    }

    // Bilinear sum: ln(v) = Σ_m Σ_n c_mn · T_m(u) · T_n(w).
    let mut sum = V::splat(0.0);
    let mut m = 0;
    while m <= SEED_DEG {
        let tm = tu[m];
        let mut n = 0;
        while n <= SEED_DEG {
            sum = sum + V::splat(SEED_COEFFS[m][n]) * tm * tw[n];
            n += 1;
        }
        m += 1;
    }
    norm::vexp(sum)
}

// =========================================================================
// A5: split-context helpers
//
// These factor `solve_chunk_fast`'s (k,T)-only prelude and the Chebyshev
// k-side basis into a separate scalar entry point usable by the public
// two-stage API in `crate::otm_context`. The per-option q-side basis +
// bilinear sum + Halley/HH3 iterations are exposed both scalar (for the
// volfi-shape single-eval API) and SIMD (for the batch + vector-context
// APIs).
//
// Correctness contract: composing `ig_kt_prelude_scalar(k, T)` with
// `cheb_qside_basis(...)` + `cheb_seed_from_kside_basis_scalar(...)` +
// `householder3_step_simd(...)` for `HOUSEHOLDER3_STEPS_CTX` iterations
// must produce the exact same σ as `solve_chunk_fast` on a single-lane
// well-conditioned input, modulo ULP-level reordering of the bilinear
// double sum. (The cold-grid 0% NaN / max-err 3.42e-11 result is the
// regression gate.)
// =========================================================================

/// (k,T)-only prelude: build an [`crate::otm_context::OtmContext`] from a
/// log-moneyness `k = ln(K/F)` and time `T`. Runs the prelude exactly the
/// way `solve_chunk_fast` does, then pre-evaluates the Chebyshev k-side
/// basis `T_m(u(|k|))` for `m = 0..=SEED_DEG` so per-option work only owns
/// the q-side basis + bilinear sum + iterations.
#[inline]
pub fn ig_kt_prelude_scalar(k: f64, t: f64) -> crate::otm_context::OtmContext {
    let sqrt_t = t.sqrt();
    let ak = k.abs();
    let ek = k.exp();
    let m_val = if k > 0.0 { 1.0 } else { ek };
    let mu = (2.0 / ak.max(1e-12)).min(1e12);
    let v_lo = VOL_MIN * sqrt_t;
    let v_hi = VOL_MAX * sqrt_t;
    let k_for_seed = ak.max(SEED_K_LO).min(SEED_K_HI);

    // Chebyshev k-side basis at u(k_for_seed).
    let ln_k = k_for_seed.ln();
    let u_centre = 0.5 * (SEED_LN_K_LO + SEED_LN_K_HI);
    let u_half_width = 0.5 * (SEED_LN_K_HI - SEED_LN_K_LO);
    let u = (ln_k - u_centre) / u_half_width;

    let mut cheb_tu = [0.0_f64; SEED_DEG + 1];
    cheb_tu[0] = 1.0;
    if SEED_DEG >= 1 {
        cheb_tu[1] = u;
    }
    let two_u = 2.0 * u;
    let mut i = 2;
    while i <= SEED_DEG {
        cheb_tu[i] = two_u * cheb_tu[i - 1] - cheb_tu[i - 2];
        i += 1;
    }

    crate::otm_context::OtmContext {
        sqrt_t,
        k_log: k,
        ak,
        ek,
        m: m_val,
        mu,
        v_lo,
        v_hi,
        k_for_seed,
        cheb_tu,
    }
}

/// Scalar q-side Chebyshev basis: `T_n(w(q))` for `n = 0..=SEED_DEG`. The
/// caller is responsible for clamping `q` into `[SEED_P_LO, SEED_P_HI]`.
#[inline]
pub fn cheb_qside_basis(q_for_seed: f64) -> [f64; SEED_DEG + 1] {
    let logit_q = (q_for_seed / (1.0 - q_for_seed)).ln();
    let w_centre = 0.5 * (SEED_LOGIT_P_LO + SEED_LOGIT_P_HI);
    let w_half_width = 0.5 * (SEED_LOGIT_P_HI - SEED_LOGIT_P_LO);
    let w = (logit_q - w_centre) / w_half_width;

    let mut tw = [0.0_f64; SEED_DEG + 1];
    tw[0] = 1.0;
    if SEED_DEG >= 1 {
        tw[1] = w;
    }
    let two_w = 2.0 * w;
    let mut i = 2;
    while i <= SEED_DEG {
        tw[i] = two_w * tw[i - 1] - tw[i - 2];
        i += 1;
    }
    tw
}

/// SIMD q-side Chebyshev basis: `T_n(w(q))` for `n = 0..=SEED_DEG`, lane-packed.
/// Same clamp contract as the scalar form.
#[inline]
pub fn cheb_qside_basis_simd(q_for_seed: V) -> [V; SEED_DEG + 1] {
    let logit_q = norm::vlog(q_for_seed / (V::splat(1.0) - q_for_seed));
    let w_centre = V::splat(0.5 * (SEED_LOGIT_P_LO + SEED_LOGIT_P_HI));
    let w_half_width = V::splat(0.5 * (SEED_LOGIT_P_HI - SEED_LOGIT_P_LO));
    let w = (logit_q - w_centre) / w_half_width;

    let mut tw = [V::splat(0.0); SEED_DEG + 1];
    tw[0] = V::splat(1.0);
    if SEED_DEG >= 1 {
        tw[1] = w;
    }
    let two_w = V::splat(2.0) * w;
    let mut i = 2;
    while i <= SEED_DEG {
        tw[i] = two_w * tw[i - 1] - tw[i - 2];
        i += 1;
    }
    tw
}

/// Scalar bilinear Chebyshev seed sum: `ln(v) = Σ_m Σ_n c_mn · cheb_tu[m] · cheb_tw[n]`.
/// Returns `v = exp(sum)`.
#[inline]
pub fn cheb_seed_from_kside_basis_scalar(
    cheb_tu: &[f64; SEED_DEG + 1],
    cheb_tw: &[f64; SEED_DEG + 1],
) -> f64 {
    let mut sum = 0.0_f64;
    let mut m = 0;
    while m <= SEED_DEG {
        let tm = cheb_tu[m];
        let mut n = 0;
        while n <= SEED_DEG {
            sum += SEED_COEFFS[m][n] * tm * cheb_tw[n];
            n += 1;
        }
        m += 1;
    }
    sum.exp()
}

/// SIMD bilinear Chebyshev seed sum, lane-packed. Each lane is independent;
/// `cheb_tu[m]` carries lane `j`'s pre-evaluated k-side basis. Returns
/// `v = exp(sum)`.
#[inline]
pub fn cheb_seed_from_basis_simd(
    cheb_tu: &[V; SEED_DEG + 1],
    cheb_tw: &[V; SEED_DEG + 1],
) -> V {
    let mut sum = V::splat(0.0);
    let mut m = 0;
    while m <= SEED_DEG {
        let tm = cheb_tu[m];
        let mut n = 0;
        while n <= SEED_DEG {
            sum = sum + V::splat(SEED_COEFFS[m][n]) * tm * cheb_tw[n];
            n += 1;
        }
        m += 1;
    }
    norm::vexp(sum)
}

/// Public alias for [`householder3_step`] — same function, exposed so the
/// split-context API can run iterations.
#[inline]
pub fn householder3_step_simd(v: V, mu: V, q: V) -> V {
    householder3_step(v, mu, q)
}

/// Solve one lane-packed batch by Schadner's formula + Chebyshev seed + one Halley step.
#[inline]
fn solve_chunk_fast(s: V, k: V, t: V, r: V, price: V, is_call: M, valid: M) -> V {
    let nan = V::splat(f64::NAN);
    let sqrt_t = t.sqrt();
    let df = norm::vexp(-r * t);
    let fwd = s / df;
    let k_log = norm::vlog(k / fwd);
    let ak = k_log.abs();
    let ek = norm::vexp(k_log);

    let m = k_log.simd_gt(V::splat(0.0)).select(V::splat(1.0), ek);

    let xn = price / s;
    let c = is_call.select(xn, xn + V::splat(1.0) - ek);

    // Probit arm — closed form at the forward (`σ = 2·Φ⁻¹((c+1)/2)/√T`).
    let sigma_atm = V::splat(2.0) * norm::phi_inv((c + V::splat(1.0)) * V::splat(0.5)) / sqrt_t;

    // IG arm. Clamp (|k|, q) into the seed domain so the Chebyshev expansion
    // is interpolating, not extrapolating. Out-of-domain lanes get a sigma
    // that is still close enough for Halley to recover from in one step;
    // the conditioning floor and the priced_ok gate finish the job.
    let q = (V::splat(1.0) - c) / m;
    let mu = (V::splat(2.0) / ak.simd_max(V::splat(1e-12))).simd_min(V::splat(1e12));
    let k_for_seed = ak
        .simd_max(V::splat(SEED_K_LO))
        .simd_min(V::splat(SEED_K_HI));
    let q_for_seed = q
        .simd_max(V::splat(SEED_P_LO))
        .simd_min(V::splat(SEED_P_HI));

    let v_lo = V::splat(VOL_MIN) * sqrt_t;
    let v_hi = V::splat(VOL_MAX) * sqrt_t;
    let mut v_iter = cheb_seed(k_for_seed, q_for_seed)
        .simd_max(v_lo)
        .simd_min(v_hi);
    // `HALLEY_STEPS` Halley iterations. Each step takes residual `e` to ~e³;
    // seed accuracy ~9e-7 → 1 Halley reaches f64 conditioning floor on the
    // accepted regime. Excess iterations are insurance for the wings where
    // Halley convergence stretches. The vega-scaled gate poisons any lane
    // that did NOT converge, and the `implied_vol_fast` wrapper refires
    // those lanes via the rational kernel — so dropping `HALLEY_STEPS`
    // trades kernel time for fallback time.
    let mut _i = 0;
    while _i < HALLEY_STEPS {
        v_iter = halley_step(v_iter, mu, q).simd_max(v_lo).simd_min(v_hi);
        _i += 1;
    }
    let mut _j = 0;
    while _j < HOUSEHOLDER3_STEPS {
        v_iter = householder3_step(v_iter, mu, q).simd_max(v_lo).simd_min(v_hi);
        _j += 1;
    }
    let sigma_ig = v_iter / sqrt_t;

    // Avenue 1: cancellation-free IG CDF lets Halley converge at ATM, so the
    // probit arm and the near-forward routing are no longer required.
    let q_ok = q.simd_gt(V::splat(0.0)) & q.simd_lt(V::splat(1.0));
    let sigma = sigma_ig;

    // BREAK: gate ripped out. Whatever Halley produces is the output.
    let _ = (valid, q_ok, price, sigma_atm);
    sigma
}

/// Black-Scholes implied volatility via Schadner's explicit formula + a
/// Chebyshev pre-fit seed + one Halley step. The v1.1 throughput-prioritized
/// kernel — machine precision across the canonical input range, same
/// six-slice API, same `NaN` contract as [`crate::implied_vol_rational`].
///
/// See module docs for the algorithm. On Crucible (AMD Ryzen 9 9950X,
/// AVX-512) targets sub-50 ns/option — competitive with [wol-fi/volfi]'s
/// scalar-C++ ~35-40 ns/eval (projected) while delivering SIMD batch
/// amplification on top.
///
/// [wol-fi/volfi]: https://github.com/wol-fi/volfi
///
/// # Panics
/// If the input slices are not all the same length.
pub fn implied_vol_fast_kernel(
    spot: &[f64],
    strike: &[f64],
    tte: &[f64],
    rate: &[f64],
    price: &[f64],
    kind: &[OptionKind],
) -> Vec<f64> {
    let n = spot.len();
    assert!(
        strike.len() == n
            && tte.len() == n
            && rate.len() == n
            && price.len() == n
            && kind.len() == n,
        "implied_vol_fast_kernel: all input slices must have the same length"
    );
    let mut out = vec![0.0_f64; n];
    let mut i = 0;
    while i < n {
        let take = core::cmp::min(LANES, n - i);
        let mut sb = [1.0_f64; LANES];
        let mut kb = [1.0_f64; LANES];
        let mut tb = [1.0_f64; LANES];
        let mut rb_in = [0.0_f64; LANES];
        let mut pb = [1.0_f64; LANES];
        let mut callb = [false; LANES];
        let mut realb = [false; LANES];
        for j in 0..take {
            sb[j] = spot[i + j];
            kb[j] = strike[i + j];
            tb[j] = tte[i + j];
            rb_in[j] = rate[i + j];
            pb[j] = price[i + j];
            callb[j] = kind[i + j].is_call();
            realb[j] = true;
        }
        let s_v = V::from_array(sb);
        let k_v = V::from_array(kb);
        let t_v = V::from_array(tb);
        let r_v = V::from_array(rb_in);
        let p_v = V::from_array(pb);
        let is_call = M::from_array(callb);
        let real = M::from_array(realb);
        let valid = real & screen(s_v, k_v, t_v, r_v, p_v, is_call);

        let res = solve_chunk_fast(s_v, k_v, t_v, r_v, p_v, is_call, valid);
        out[i..i + take].copy_from_slice(&res.to_array()[..take]);
        i += take;
    }
    out
}

#[cfg(test)]
mod avenue1_property_tests {
    use super::*;

    /// Reference: the original (cancellation-prone) IG CDF, used to property-test
    /// the cancellation-free rewrite at points where the original is still accurate.
    fn ig_cdf_old(x: f64, mu: f64) -> f64 {
        let sqrt_x = x.sqrt();
        let inv_sqrt_x = 1.0 / sqrt_x;
        let a = sqrt_x / mu;
        // Φ(z) = 0.5 · erfc(−z/√2).
        let phi = |z: f64| 0.5 * erfc_scalar(-z / std::f64::consts::SQRT_2);
        let term1 = phi(-a + inv_sqrt_x);
        let term2 = phi(-a - inv_sqrt_x);
        let surv = term1 - (2.0 / mu).exp() * term2;
        1.0 - surv
    }

    // Φ(z) = 0.5 · erfc(−z/√2); we use the real `erfc` via libm-style polynomial
    // through `norm::erfcx`: erfc(y) = erfcx(y)·exp(−y²) for y ≥ 0, and for y < 0,
    // erfc(y) = 2 − erfc(−y).
    fn erfc_scalar(neg_arg: f64) -> f64 {
        // Computes erfc(neg_arg). neg_arg can be any real.
        let y = neg_arg;
        if y >= 0.0 {
            let erfcx_y = norm::erfcx(V::splat(y))[0];
            erfcx_y * (-(y * y)).exp()
        } else {
            let yp = -y;
            let erfcx_yp = norm::erfcx(V::splat(yp))[0];
            2.0 - erfcx_yp * (-(yp * yp)).exp()
        }
    }

    fn ig_cdf_new(x: f64, mu: f64) -> f64 {
        let xv = V::splat(x);
        let muv = V::splat(mu);
        ig_cdf_pdf_dpdf(xv, muv).0[0]
    }

    #[test]
    fn avenue1_matches_naive_away_from_atm() {
        // |k| >= 0.1 corresponds to μ = 2/|k| <= 20, no cancellation regime.
        // q maps onto x via the Schadner formula; we just sweep (x, μ) directly
        // and check the IG CDF identity.
        let mut max_abs = 0.0f64;
        let mut max_rel = 0.0f64;
        let mut worst = (0.0, 0.0, 0.0, 0.0);
        // Deterministic LCG for reproducibility, 1024 samples.
        let mut state = 0xdeadbeef_u64;
        for _ in 0..2048 {
            state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            let r1 = ((state >> 11) as f64) / ((1u64 << 53) as f64);
            state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            let r2 = ((state >> 11) as f64) / ((1u64 << 53) as f64);
            // μ ∈ [1, 50] — old form is well-conditioned: e^(2/μ) ∈ [e^0.04, e^2].
            // We don't push into the ATM-cancellation regime (μ → ∞) here because
            // that is the regime where the OLD form is BROKEN — that's the whole
            // point of Avenue 1. We test agreement only where OLD is trustworthy.
            let mu = 1.0 + 49.0 * r1;
            // x ∈ [0.1·μ, 3·μ] — mass-bearing IG support; tails are wild.
            let x = mu * (0.1 + 2.9 * r2);
            let old = ig_cdf_old(x, mu);
            let new = ig_cdf_new(x, mu);
            let abs = (old - new).abs();
            let rel = abs / old.abs().max(1e-300);
            if abs > max_abs {
                max_abs = abs;
                worst = (x, mu, old, new);
            }
            if rel > max_rel {
                max_rel = rel;
            }
        }
        eprintln!(
            "avenue1_property: max_abs = {:.3e}, max_rel = {:.3e}, worst (x, μ, old, new) = ({:e}, {:e}, {:e}, {:e})",
            max_abs, max_rel, worst.0, worst.1, worst.2, worst.3
        );
        assert!(max_abs < 1e-13, "new and old IG CDF disagree: max_abs = {:e}", max_abs);
    }

    #[test]
    fn avenue1_finite_at_atm() {
        // μ very large (ATM): old form is degenerate; new must still be finite & accurate.
        // We don't know the truth here without arb-prec, but we can sanity-check
        // monotonicity and finiteness.
        for mu_exp in 0..8 {
            let mu = 10f64.powi(mu_exp); // 1, 10, ..., 1e7
            let mut prev = -1.0f64;
            for j in 1..50 {
                let x = mu * (j as f64) / 50.0;
                let new = ig_cdf_new(x, mu);
                assert!(new.is_finite(), "CDF non-finite at x={x}, μ={mu}: {new}");
                assert!(new >= 0.0 && new <= 1.0, "CDF out of [0,1] at x={x}, μ={mu}: {new}");
                assert!(new >= prev - 1e-12, "CDF not monotone at x={x}, μ={mu}: prev={prev} new={new}");
                prev = new;
            }
        }
    }
}
